import json
import os
import time
import threading
import redis
from typing import List, Union, Optional, Dict
from sqlalchemy.orm import Session
from src.core.models import Candlestick, Trade, Signal, SignalType
from src.core.orm_models import SignalAudit
from src.strategies.base import BaseStrategy
from src.core.risk_manager import RiskManager, AccountService
from src.core.execution import ExecutionEngine
from src.core.clock import Clock
from src.core.interfaces import IOrderRepository

# Redis Config
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))

class StrategyEngine:
    def __init__(self, db_session: Session, clock: Clock, order_repository: Optional[IOrderRepository] = None):
        self.db = db_session
        self.clock = clock
        self.strategies: Dict[str, List[BaseStrategy]] = {} # Key: product_id
        # Initialize Services
        self.account_service = AccountService()
        self.risk_manager = RiskManager(self.account_service)
        self.execution_engine = ExecutionEngine(db_session, clock, order_repository)
        
        # System State & Heartbeat
        self.redis_client = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=True)
        self.running = True
        self.heartbeat_thread = None

    def startup(self):
        """
        Runs startup checks and starts background services.
        """
        self._check_system_state()
        self._reconcile_balance()
        self._start_heartbeat()

    def _reconcile_balance(self):
        """
        Startup Reconciliation
        Force overwrite Redis balance from actual Exchange API.
        """
        print("💰 Reconciling Balance...")
        try:
            # Note: For now, AccountService might be a mock or use CCXT internally.
            # We assume it has a get_balance method.
            balance = self.account_service.get_balance("USDT")
            # Update Redis (state:balance:total)
            self.redis_client.set("state:balance:USDT", str(balance))
            print(f"✅ Balance Reconciled: {balance} USDT")
        except Exception as e:
            print(f"⚠️  Balance Reconciliation Failed: {e}. Using DB/Redis state.")

    def _check_system_state(self):
        """
        Checks 'system:state'. If 'LOCKDOWN', enters a paused loop.
        """
        print("🔍 Checking System State...")
        while True:
            try:
                state = self.redis_client.get("system:state")
                if state == "LOCKDOWN":
                    print("⚠️  SYSTEM LOCKED (LOCKDOWN). Waiting for manual resume...")
                    time.sleep(5)
                else:
                    print(f"✅ System State: {state or 'OK'}. Proceeding.")
                    break
            except Exception as e:
                print(f"❌ Error checking system state: {e}. Retrying...")
                time.sleep(2)

    def _start_heartbeat(self):
        """
        Starts the heartbeat background thread.
        """
        def heartbeat_loop():
            print("💓 Heartbeat Service Started.")
            while self.running:
                try:
                    # TTL 3 seconds, Update every 1s
                    self.redis_client.setex("heartbeat:python", 3, "1")
                    time.sleep(1.0)
                except Exception as e:
                    print(f"💓 Heartbeat Failed: {e}")
                    time.sleep(1.0)
        
        self.heartbeat_thread = threading.Thread(target=heartbeat_loop, daemon=True)
        self.heartbeat_thread.start()

    def add_strategy(self, strategy: BaseStrategy):
        if strategy.product_id not in self.strategies:
            self.strategies[strategy.product_id] = []
        self.strategies[strategy.product_id].append(strategy)
        print(f"Registered strategy: {strategy.strategy_id} for {strategy.product_id}")

    def on_market_data(self, data: Union[Candlestick, Trade]):
        """
        Callback triggered by DataConsumer when new market data arrives.
        """
        # Dispatch to strategies for this product
        strategies = self.strategies.get(data.product_id, [])
        for strategy in strategies:
            try:
                if isinstance(data, Trade):
                    signal = strategy.on_trade(data)
                else:
                    signal = strategy.on_candle(data)
                
                if signal:
                    self.process_signal(signal, data if isinstance(data, Candlestick) else None)
            except Exception as e:
                print(f"Error in strategy {strategy.strategy_id}: {e}")

    def process_signal(self, signal: Signal, candle: Optional[Candlestick]):
        """
        Handle the signal generated by a strategy.
        First validates with RiskManager, then forwards to Execution.
        Logs everything to SignalAudit.
        """
        if signal.type == SignalType.NO_SIGNAL:
            return

        # 1. Risk Check
        is_passed, risk_msg = self.risk_manager.check_risk(signal)
        
        order_id = None
        # 2. Execution
        if is_passed:
            print(f"✅ SIGNAL ACCEPTED: {signal.type}. Forwarding to Execution Engine...")
            order_id = self.execution_engine.execute_signal(signal, candle)
        
        # 3. Audit Logging
        try:
            audit = SignalAudit(
                timestamp=int(self.clock.now() * 1000),
                strategy_id=signal.strategy_id,
                product_id=signal.product_id,
                signal_type=signal.type.value,
                risk_status="PASS" if is_passed else "REJECT",
                risk_message=risk_msg,
                order_id=order_id,
                details_json=json.dumps({
                    "candle": candle.model_dump(mode='json') if candle else None,
                    "signal_metadata": signal.metadata
                })
            )
            self.db.add(audit)
            self.db.commit()
        except Exception as e:
            print(f"Failed to log audit trail: {e}")
            self.db.rollback()
