from typing import List
from src.core.models import Candlestick, Signal, SignalType
from src.strategies.base import BaseStrategy

class StrategyEngine:
    def __init__(self):
        self.strategies: List[BaseStrategy] = []

    def add_strategy(self, strategy: BaseStrategy):
        self.strategies.append(strategy)
        print(f"Registered strategy: {strategy.strategy_id}")

    def on_market_data(self, candle: Candlestick):
        """
        Callback triggered by DataConsumer when new candle arrives.
        """
        # Dispatch to all strategies
        for strategy in self.strategies:
            try:
                signal = strategy.on_candle(candle)
                self.process_signal(signal)
            except Exception as e:
                print(f"Error in strategy {strategy.strategy_id}: {e}")

    def process_signal(self, signal: Signal):
        """
        Handle the signal generated by a strategy.
        In the future, this will forward to RiskManager and ExecutionEngine.
        """
        if signal.type != SignalType.NO_SIGNAL:
            print(f"⚠️  SIGNAL GENERATED: {signal}")
        else:
            # Verbose logging can be removed later
            # print(f"No signal from {signal.strategy_id}")
            pass
